name: a moi
on:
  push:
    branches: [ dave ] 
jobs:
  ansible:
    name: run playbook
    runs-on: [self-hosted, yig]
    steps:
      # Checkout : récupère le docker-compose.yml à jour depuis le dépôt
      - name: Checkout du dépôt
        uses: actions/checkout@v7
      - name: injection des vaults
        working-directory: ${{ github.workspace }}
        run: |
          cp /home/ansible/test/.vault /home/ansible/test/test/test/.vault
      - name: run ansible-playbook
        working-directory: ${{ github.workspace }}
        run: |
          ansible-playbook playbook.yml
      - name: kill them all
        run: |
          rm -rf /home/ansible/test/
